/**
 * Blur placeholders — GENERATED, DO NOT EDIT BY HAND.
 *
 * Written by scripts/generate-image-blur.mjs. Run `npm run blur` after
 * adding or replacing an image in public/images/.
 *
 * Each value is an eight-pixel-wide webp as a data URL, handed to
 * next/image as blurDataURL so something appears in the frame immediately
 * instead of a shimmer.
 */

export const imageBlur: Readonly<Record<string, string>> = {
  "/images/about/about-hero-2026-08.webp": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoIAAUABABoJQBOgCIBWh96AADLQH2QVQUAV8fd56LHHyx+MyYzt7EAAAA=",
  "/images/about/geographic-scope-2026-08.webp": "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAACwAQCdASoIAAQABABoJZQAAxbJHNEAAP1PHiDzqTM9uyFAAAA=",
  "/images/about/mission-community-2026-08.webp": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAACQAQCdASoIAAUABABoJZwAAp0ispwAzCUW+x0wxMF6ae6OmiQB26OAAAA=",
  "/images/blog/rising-the-heat-declining-the-productivity.webp": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAABQAgCdASoIAAQABABoJaACdH8IwBb/4HocxoAA9kfF31k6zUfWNim+oJmuExGuMJLyL7+L+ZgaAA==",
  "/images/blog/the-carbon-league.webp": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACwAQCdASoIAAQABABoJZQCdAD0cgEQAP7pXXIJNzN8r8Td8SiJBOIAV9QAAA==",
  "/images/blog/thirsty-ai.webp": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoIAAQABABoJYwCdAD0gbJgAP7ytCbdMugiNm3FWSBWMcBE82kH+v8VegA=",
  "/images/brand/climatewatch-logo-red.webp": "data:image/webp;base64,UklGRngAAABXRUJQVlA4WAoAAAAQAAAABwAAAwAAQUxQSCEAAAAAHoDV0qfLxh8tnst9+87IEA47SklOMkYGHlteZl5eYTsAVlA4IDAAAACwAQCdASoIAAQABABoJQBdgCB/ZUZAAP7mCx9HmcfgnTOYZrkm7W6bsy2VUb6AAAA=",
  "/images/brand/climatewatch-logo.webp": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4WAoAAAAQAAAABwAAAwAAQUxQSCEAAAAAAA1IWzo1AQAAPMme5L0FAAAfYGNfUwEAACBESUhDFAAAVlA4ICgAAADQAQCdASoIAAQABABoJZQCw7ERHyhmBAD+8tH6n3EfTozKnxkIcUAA",
  "/images/home/home-closing-2026-08.webp": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoIAAUABABoJQBOgB5P38AAAP2Uqp/BvE9wRfL96UFmooxEG/bWta5sAAA=",
  "/images/home/home-hero-2026-08.webp": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoIAAUABABoJYwCdAEfg66yYAD2ot0c17va35xzoJtuoatLBf4MXwqIRTgcAA==",
  "/images/home/home-hero-mobile-2026-08.webp": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoIAAwABABoJZAAAuXc8qKAAP3jYzCCUJjtgIrCqAvD+uwjSLWqlWuDYqzxHTY4o/TzPQAA",
  "/images/home/home-introduction-2026-08.webp": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoIAAUABABoJagCdAEQCtD+mAD7pOt0q7TrDc/1yakf64DtL/sOnZxgAAA=",
  "/images/home/how-we-work-ploughing-2026-08.webp": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADQAQCdASoIAAcABABoJYwCdAEUpOOW0AD330HPCAvrggv+4HB4KLznDAAAAA==",
  "/images/partners/climate-forward-pakistan.png": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4WAoAAAAQAAAABwAABQAAQUxQSDEAAAAAAAUwbxRQBgAAJV7hUYU9AAAvjcL/4y0AAQBpzfJzAAI3Pz1aVkZHRUM8PCgwOz9BAFZQOCA6AAAAkAEAnQEqCAAGAAQAaCWwAnQA2u2AAMxQnjyTeLYizyfx+LaXBZRF0x+vQ2pqWgTr5RAJ+9238Gt2AA==",
  "/images/partners/fridays-for-future-pakistan.png": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4WAoAAAAQAAAABwAABwAAQUxQSEAAAAABZ6CgbRumGu8BHKO/0IiIEAxHxuEGRQFARgG82L2fCFr46uOpwCKsgRYqRvQ/UgOcqW6TPxFtINpt8pypUgMAVlA4IEIAAABwAQCdASoIAAgABABoJbACdAGIQAD+4eHuZ0An7w+mj90Se81guOY8jV43YXxiiy3O9r+9zL/uxTuVYhP1lF4AAAA=",
  "/images/partners/gilgit-baltistan-climate-watch.png": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQAgCdASoIAAgABABoJagCdH8AFcuTbFjwAP7YZqXm3wK4lfD1xHGNieNMm0LKAxOuy9fNwQI40UojtW/WzSsUm8YAAA==",
  "/images/partners/glacier-school.png": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoIAAsABABoJZQCw7EU+CfVYgAA/uuwiI7yCgIOcP7aYlbNOS95LeE3DuLN6+9EOxef4bpSAjfXLetDPeC9XzBKkuKnAAAA",
  "/images/partners/herspace-2026-08.png": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4WAoAAAAQAAAABwAABAAAQUxQSCkAAAAABCpFYj4fkWgLm8vCdUahmGyfnXWLTLJ2kY2Dn7BlYzq8w7zB0MW2owBWUDggNAAAALABAJ0BKggABQAEAGglqAJ0AQ67BIAA/sshY16PXMT7yItmxo2BVLN/NeT5rnQbdggAAAA=",
  "/images/partners/ibtida.png": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4WAoAAAAQAAAABwAAAwAAQUxQSCEAAAAAbag/AAMBAABl/2YABgEAAAmeSUhDPhIDATctMTIuKCMAVlA4IDIAAACwAQCdASoIAAQABABoJQBYdh6RkC+gAPziCU6BrTBW9wPTHL3+IA7KDVpslA21nAAAAA==",
  "/images/partners/institute-of-strategic-studies-islamabad.png": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoIAAgABABoJQBdgB5vdwsAAP7iVaLAW6t1WHNhEvQmvTJmijWnJPHYYufPGu9Ok4FiUWKAAAA=",
  "/images/partners/karakoram-impact-network.png": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoIAAgABABoJQBOgCB/L9YJqAAA/u5mOf9PO0d9LkSmApChe86S97O07T1t5slho4mzLWDTxlcVlpcMBpnjwAAA",
  "/images/partners/misbah-sports-academy.png": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4WAoAAAAQAAAABwAABQAAQUxQSDEAAAAAAQADTjwAAgACAEOLekUcAAILHzxWMQwDbH17a6M0f2Rlf3l1lYOQgwAOIj5AIRACAFZQOCBOAAAA8AEAnQEqCAAGAAQAaCWwAnQA9Kcx6KwAAP7m7yLR7nmO4/FSDXgO9I9jLoSdQmWq4IhDfz2P1mbAIGH2//Jyn+uam/4/zOiNNcZXUAAA",
  "/images/partners/nccb.png": "data:image/webp;base64,UklGRsAAAABXRUJQVlA4WAoAAAAQAAAABwAABwAAQUxQSEEAAAAAAgAyIWw1AgAAVYaJnG8xCAhkwevtrpE4X5Oox86yeCc8kcHC1aiKRQBpj9HLmWQ1AFF7W4JvDwMAAQAZPRYAAgBWUDggWAAAAPABAJ0BKggACAAEAGglsAJ0APSQGM+egAD+MvCTzmiH8duhE7y4d58LNugXsNfBBECOr537Pv07MBsmD/ByRxd3t8FH+gf+Rr8gxJuN1oLv+aH39ze3YAA=",
  "/images/partners/nustainable-mono.png": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4WAoAAAAQAAAABwAABQAAQUxQSDEAAAAAAAAaPEYbAAAAIIGoqXsgAABmtamktWAANyxSWF9NShyMZXRjamd5dicqJSouLygdAFZQOCAkAAAAsAEAnQEqCAAGAAQAaCWkAAMWXI5KwAD+8Udk5LomsmLwBgAA",
  "/images/partners/nutrashine.png": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4WAoAAAAQAAAABwAABwAAQUxQSEEAAAAAAC20+Pi0LQAw6//+/v/rMLD/+f//+f+w9P////////T0////////9LD/+f//+f+wMOv//v7/6y8ALrT397QuAABWUDggJgAAAJABAJ0BKggACAAEAGglnAAC51m2AAD+88iBVLppuZ6Ltb6AAAAA",
  "/images/partners/progressive-climate-foundation.png": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4WAoAAAAQAAAABwAABwAAQUxQSEEAAAAAAC2/5uW9LAAv7retrbnuLMaacP//b56/02be///aZsdDKdr2+NQhR5efFMK7EKOWNPWjh4Sk9TIALMPr7MErAABWUDggSgAAABACAJ0BKggACAAEAGglsAJ0BioOSvTjdAAA+gb3yJQUTWqOhuwqXOwLFQKl1hvqnM2JJpBmZzbeiTbSZSlxycPjDcgfqUcNeAAA",
  "/images/partners/sustainable-development-policy-institute.png": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4WAoAAAAQAAAABwAAAwAAQUxQSCEAAAAARNFxAQEGAgH5//qHYGJ6aff//HJTXUw8P85sAAQFBAUAVlA4ICwAAACwAQCdASoIAAQABABoJZQAAp1ynyOAAPJsk44IbouP2cW4YLq6Cuk74BgAAA==",
  "/images/partners/taqalum.png": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACwAQCdASoIAAMABABoJQBOgCIj27JAAP7J4+7r/TwQFF2nsNqICK0OoyyjKAAA",
  "/images/partners/the-zameek-community.png": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoIAAgABABoJbACdAYqXkUaecAA/slBclr1IxAF8f52tc5q6cWI+dM/TNag/mQjtSl9yaFQDWimurxQQymotiJJ1/DtPxRQHxWFeFtRQAA=",
  "/images/programmes/education-sustainable-development-2026-08.webp": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAABwAQCdASoIAAUABABoJaQAAlJNQAD+TSW4U06ZSgTNmwSe9J+0miAAAAA=",
  "/images/programmes/glacier-school-2026-08.webp": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADQAQCdASoIAAUABABoJQBOkCYjAa3cxAD5UjBOJvOUQ+5446iJeQ3lkyUgAA==",
  "/images/programmes/international-climate-policy-2026-08.webp": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoIAAUABABoJYwCdADyfvaAAP6jFA0qyj0Wh1WXA2m8tca+sG9a1BuwAAA=",
  "/images/programmes/programmes-hero-debris-2026-08.webp": "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAACQAQCdASoIAAUABABoJZwAApeIMAAA+fNvQgONB5Zw0esbT0/1gIAA",
  "/images/programmes/research-development-2026-08.webp": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoIAAUABABoJaACdADb0g4AAP6HQ2ceAxtDFTSwQ0mevWlubhMRhnWAAAA=",
  "/images/projects/autonomous-drones.webp": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACQAQCdASoIAAUABABoJQBOgBsyX/AA9dyTqdYKpzg24ykmwJG1jw2ayPsQCgoMVKAAAA==",
  "/images/projects/climate-bethaak-2026-08.webp": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoIAAcABABoJbACdAEUmgFDAAD2d2uW1G1FQgvBHA7tkGNd9/afOzhptag5uK/iCsAAAA==",
  "/images/projects/glacier-school-classroom-2026-08.webp": "data:image/webp;base64,UklGRjIAAABXRUJQVlA4ICYAAACwAQCdASoIAAUABABoJZwAAxamELUgAM3xNBDqZKOyHMoQ6JMCAA==",
  "/images/projects/projects-hero-mountain-2026-08.webp": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACwAQCdASoIAAUABABoJYwCdADx+HEAAM443cCDGLmVX7R4CC9TXuwA4svZkeAA",
  "/images/projects/unfccc-negotiations-bonn-2026-08.webp": "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAACQAQCdASoIAAQABABoJaQAAsZrVCAA/kkalmnqsi2SS+YLIwXw4AAA",
  "/images/publications/ace-at-sb64.webp": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAAAQAgCdASoIAAsABABoJZACdAEUpKQ0Y9gAAP6Ru9EzvEoB1gPh6TAmXBzcu3uP7OxFi2HaKbs4XOgQ1vMgAA==",
  "/images/publications/from-disaster-response-to-climate-resilience.webp": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoIAAsABABoJaQAAp257SHoAAD+7YsbUEgFaYch73ETv2CR/3kAAAAA",
  "/images/publications/mountain-frontlines-youth-futures.webp": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoIAAsABABoJQBdgCPwjl8LAAD+6EwKhvcFAXCOPYGPPmE+GKO4g6npvpuytYH9xAA=",
  "/images/publications/pakistan-climate-budget-reduction-summary.webp": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoIAAsABABoJZQCdAEO4aeZAAD+6zZxrC2vrbvvkHOb4JAFCAYcTaHCGJHMc4Rcwf64IAr0b2oCLMa8wAA=",
  "/images/publications/pakistan-climate-budget-reduction.webp": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoIAAsABABoJbACdAEUmcAfjwAA/phcPxQZspdAVccUc6lW+WAHt3gjkRfDPy0spUDJzn/StIRzY0wquAA=",
  "/images/publications/state-of-play-at-bonn.webp": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoIAAsABABoJZgCdAEegKCQNAD+Ztosi2fW9Qi+y/dFwQl4qqm4uBvAWbzy0JzTIgA3h4LR3mXMrm8enQAAAA==",
  "/images/publications/wildlife-of-northern-pakistan.webp": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAQCdASoIAAoABABoJQBOgB8xtMWPLMAA/sX7sG8WvAibi5e6FLTqrHkmivWDuLZV7geYJI5soFkHgAA=",
  "/images/research/research-fieldwork-focus-2026-08.webp": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoIAAYABABoJZQC7ADdaQvsAAD+hrMkeOkMf7TBWUfa4XFmrouQPCWdFMtBjQ/eAAA=",
  "/images/research/research-hero-2026-08.webp": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAACwAQCdASoIAAUABABoJQBOgCHXYJAAAP55MOW/rFWCC+UsOBRk3VLTAAA=",
  "/images/team/ahbab-ullah.webp": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoIAAoABABoJZgAAvxTZZzdsAD+ASeV3zi0XNS1MUkW0lXW5SVn7U6cb95OTMJ5en+mGUVEe6U2/z05tIxemUXaKAA=",
  "/images/team/ahmad-rafay-alam.webp": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoIAAoABABoJYwCdAEfB/17tneAAP7m5z5p32GYRTDJRSMPcVCOTCTsGTDhxmiTx1t3RdayUdCUQI7AUjK9CBjX+AAAAA==",
  "/images/team/ahmed-yar.webp": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoIAAoABABoJQBOgCB/r6/ZdAD+4o0qLBo1Sv/YMAVlh/qcqQFcGHTafOqeitdcwYRsVC3n93x8XupD6Sh0UU+HAAA=",
  "/images/team/aimen-tahir.webp": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoIAAoABABoJZQCsAED9/GTkAD+YQFes6uWScGPbFdUibLSscr+rG0B/jkzL+PkEegagvTogQAAAA==",
  "/images/team/alexandra-schiller.webp": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAwAgCdASoIAAoABABoJYwCdAYt9bLRKc1IAAD+YBj9nNen2OBL3rUr4DyouwhPdbt7jIc25lbkhntRwoc6xIr0XBbnmGl54AA=",
  "/images/team/amin-fahim.webp": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAQAgCdASoIAAoABABoJZQCw7EfB/ssMXAAAPzi7kVrD497x3Tv6KzSbX/53gPHqO5Lmj/8YsBIflsxr52FLihpbwFgYkINwAA=",
  "/images/team/amjad-ali.webp": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAQAgCdASoIAAoABABoJZwAD4ANauxS2lEgAP7rwdsGCAi9r3E32sDY95SfcXt/k5a9xMKTmwmfscAMo+TGmAAA",
  "/images/team/anam-rathor.webp": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoIAAoABABoJYgCdAD0lhq1BwAAzjIjY9KmhuWOyihADv7R/CJ3ADa13/MKMtMXfpaISIphDM40pM6HTDWkfAKuEAA=",
  "/images/team/anfal-nadir.webp": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoIAAoABABoJbACdAED6/EYAAD+lEFSfLwqbarvr1MDM3BE1DUcrEn1Fj6V/u5kfMOLzZDx8NOC3Iu8V2Jw7D/a6OeAAA==",
  "/images/team/aqsa-essa.webp": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoIAAoABABoJQBOgBuBEYgwAP6RVFdG4lTcCCijsgk7Fy1LaIyucRt4zcLfCy+SJdJFeq4b+DS88AAA",
  "/images/team/ariba-khan.webp": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoIAAoABABoJZQAAvrcpwGe8AAA/pQ4uf1UWyjtsOl1u1L73NShXSUuBs9+VkA48uz25li+GIlo2a6U8TqZYNhUAAA=",
  "/images/team/atia-fehmi.webp": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoIAAoABABoJQBOgB5tY60+EAD+a0w1BaxuLkR6hArCpFNsv5SwwEP50s6+r7U/geVc6kUKksCXhqSz4AA=",
  "/images/team/babar-nasir.webp": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoIAAoABABoJQAAS4iG3dKAAP6UzP94dci0RAA72pKORTCucApA5EzE0ml7z7R3QuMsXv0DwAA=",
  "/images/team/bilal-ahmed.webp": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoIAAoABABoJZQAAvwV+eVu7yAA/pFnHAg49fMGIGcO/AFsKcW5z1KtzIbPgL4NElgOu3MnQIjplY7rwIAAAA==",
  "/images/team/didar-ali.webp": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACwAQCdASoIAAoABABoJQBOgBneQe/AAP4luuKDp+EJkBkdE5+KSQY2LJDLy96fh8gLozKsXl1xS7hnKW7wAA==",
  "/images/team/ebrahim-jamali.webp": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoIAAoABABoJYwAD4kNUInc0YAA/f941zDVvsF+k7XvADPuKwGijhhDZK8MJy4Vn0xMdnNmWcTAAA==",
  "/images/team/eman-ahmad.webp": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoIAAoABABoJZwAAuds4exPAAD+5+4MihYu0VHUAXX9Leth0O6v56YDHwXGpenFIAA=",
  "/images/team/fatimah-muneer.webp": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoIAAoABABoJQAAYngcFyMwAP5ojdyKfWOAe8Bkqu7miFaWZooXM5GAmJJzzDLMvx4b1SrPe9AzAAAA",
  "/images/team/fatimah-zaheer.webp": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoIAAoABABoJZwAAvwZ6DeQgAD+sQd3G30nWg+FsDZt5TJNv5kCmAvBrlDPOQ/3/b3av9ztjq0H/QAA",
  "/images/team/fozia-tahir.webp": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQAgCdASoIAAoABABoJQBOgMVzzX4zgqwAAPWX2CC+YR8/lB+UdTvSYl+IJz3bgrOHKyg8MYZdHMjp0TcmtgnIrPhAAA==",
  "/images/team/habiba-tariq-2026-08.webp": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoIAAoABABoJbAC7ADcB290AAD+YBWqlgyW1zrQiQTXSBe+m48COiqM+EjrZHcU74tIs8K4YcPnlcBmy6ok9XzVWAAAAA==",
  "/images/team/hashma-shahzad-ahmad.webp": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoIAAoABABoJbACdAED9sX1sQAA/Kx4tNVNmz/s3U7hNmOG7KWa8+T3NmVS4Fv8PWjsbmwaGwL8rBEAAAA=",
  "/images/team/imran-saqib-khalid.webp": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAAAQAgCdASoIAAgABABoJYwCdH8AFc2g1g1IAOAKnuEeUsFfTAwji/rF3mhZQCyO91fkpO0twngAAA==",
  "/images/team/imtiaz-ali-zeb.webp": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAQAgCdASoIAAoABABoJQAB8J33+1aBIetgAPlSGHe85Q/E+9fY9T9Yj2ujnKfEwPMHRSpzNQMl6KI/qsmbCoAA",
  "/images/team/iqbal-badruddin.webp": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACwAQCdASoIAAoABABoJZQC7ADZkv+AAP7cdSNMrilVFg63e5use3eXWlpBTcAA",
  "/images/team/irshad-iqbal.webp": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoIAAoABABoJQBOgBaq4Ue1gAD4M3HfPOLi5H3T7yWIz+vrgqb0Y4AkD1T9yAoROEF0hOUBLw4rH2bJ2lj53r04AAA=",
  "/images/team/kamran-ali.webp": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoIAAoABABoJYwCsADdRpzSMAAA/uCm4IBMtu+gwX0DnHQ1U5+nCF9TdIxnCfEB1T/hDq7zfCgAAA==",
  "/images/team/mamoona-asim.webp": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAAAQAgCdASoIAAoABABoJZwAD4VRAfx/MRoAAP5hAYZ59V2TUK2iQzwZDZsL76VztbmU3mox1eO/+AAA",
  "/images/team/mehak-mir.webp": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAQAgCdASoIAAoABABoJZwAD48Pv2g3dJgAAP6RVNgGoG+sZq8pwPUBlv2OVIX91imG34Qegiex1A66TqUEhhpCKAfmEAAA",
  "/images/team/mehnaz-parveen.webp": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoIAAoABABoJbACdAD5jb7c/NsAAP4+J1FtERwtvvTwgxw4Z6Sk/IQRPhzpnaB6GJwKb/p+hiftzEAcn80I5/k3TAAAAA==",
  "/images/team/mehtab-kamal.webp": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQAgCdASoIAAoABABoJYgCdAEDe+F/qlcAAPRMHIff7/t7CCGLDfE+DHPryGX1j/ddaK/kJwPcsrCb4pacoDVGuVQAAA==",
  "/images/team/michael-muyutu.webp": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACQAQCdASoIAAoABABoJZwAAptpzLAA/un3j5mCsFwma0GeQdhBt2p5CAZV5IbJcZT9AAAA",
  "/images/team/mubeen-ishfaq-2026-08.webp": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAwAgCdASoIAAoABABoJZQAD4wRf/g9OYuj6AD+8K6lgxMWvTmR2ZEbMmvpridqCbpbGZFbgZpIzHWiDbh2IkYUQ0Q3Gp5DcAA=",
  "/images/team/muhammad-ehsaan.webp": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoIAAoABABoJZwC7ADcjKUzAAD84yx+3rLDuuLLRCvnMcefIfmwF0iiUrMg3K70gXnwn6D9tnnaoEQUsHLQYCIEAAA=",
  "/images/team/mutahira-hasnain-gillani.webp": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAAAQAgCdASoIAAoABABoJYwCdADdQsVYGqgAAP7IXr/Q69bXtqbfvg5szAYNiyaaYh8CJuPEiAAAAA==",
  "/images/team/nida-khan.webp": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACQAQCdASoIAAoABABoJZwAAllGEEAA/tgfO5eqBOwFcvmfUOlsfPa2KmHmyce93iLm62W2IQTFIffDD05GDVCAAAA=",
  "/images/team/nisha-irfan.webp": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACQAQCdASoIAAoABABoJZAAApyC24AA/rILSvM0M1SMcVJ5Hc1b37m1YnQmXP/y6yawZ5hWSz+ZfEDTn6D2/j0G7AgAAA==",
  "/images/team/pervez-aly-2026-08.webp": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAAAQAgCdASoIAAoABABoJYwCdAEf3HTGw8IAAP7n7EvqLeGB/mEivXTuBmenMNWH6gSuIrAw1n8TEHBPeQiuo4SYAAA=",
  "/images/team/rafia-imtiaz.webp": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoIAAoABABoJbACdADb01d19KwA/mAalmF2axMEG/GqtjjzbNnt124Auz42Sg6P7AXvYHOeJJX7RoOaTUCfnR3NwAA=",
  "/images/team/riaz-ahmed.webp": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAAAQAgCdASoIAAoABABoJZwCw7EedVzowNrAAP6p97azoA/jkn44RzNPopeRE7O9eDi9tkR3KsWakCdh+gofgJQAAAA=",
  "/images/team/rima-sahar.webp": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAABQAgCdASoIAAoABABoJYwC7AYqX2lvoPFt+gAA/mAYuBgEPb9bAFbz3SDwpXP5oGkYmAK8dvYpqVLwGkZVgoAA",
  "/images/team/sajida-jan.webp": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoIAAoABABoJZwAAsfoCFZeAAD+m6egaBKJbRrTZekF494WL3tO6pdWrddTUIY3Rodrq03ugxhcK4oAAAA=",
  "/images/team/sajina-rehmat.webp": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoIAAoABABoJbACdAEeofaBCEAAAP20kkuUTbCT1YRS8YOkgLC+pTRkOk3Bp9Koty2JDwMGz+l/HhIP0DLgHXXLiD58G19FgaF4AAAA",
  "/images/team/sajjad-ali.webp": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAQAgCdASoIAAoABABoJZgCdAEPAhpLrMfgAPyyb50d8vHRriGjqpfXOizvDHzcuzQm1BrKsZAzURkRJC95rqAiESEPQAAA",
  "/images/team/sania-asim.webp": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoIAAoABABoJbAC7AD0iG8MgAD+kWcOmXw0jPdLtiB2tUAKX14jsf1eH2REJZTLKUdL0LDqMgAAAA==",
  "/images/team/shahab-uddin.webp": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoIAAoABABoJZwAAl3HKEpAAAD89XosjBGSzxla7QS/BZ9xbekgeLWg8/j1I/RfaZeORSobCoAAAA==",
  "/images/team/sitara-parveen.webp": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoIAAoABABoJQBOgCP7OTIegAD+bLz3WLbmVsEukcJA27l9qIlfRRUlNeUrAdhIigzFuisSd2h+XrrExNZp0nJxtbNOJueq6AA=",
  "/images/team/syed-kiram.webp": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoIAAoABABoJQBOgB8tFvVXsAD+ovq4mi4C3ldY1SMN4LQBVKZd3kfokjwoXubP94fL7wH2ofPZCDMNYIVb6Q0cFQAAAA==",
  "/images/team/syeda-fiza-kazmi.webp": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAABQAgCdASoIAAoABABoJZQCw7EfB/wKIdn7TAAA/pFWxxSQJ0wLlru9w6x8eZiinT8UMqez/SRRrPhOYEv8FQOI7vFIAAAA",
  "/images/team/syeda-hoorain-imran.webp": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACwAQCdASoIAAoABABoJQBOgB6QPYWAAP5oQbhBsK3b9uuH/ytfb6V7dBxWkSvJIb1ueLBYL1fsSbsejf8LWaGfEh/d+axwAAA=",
  "/images/team/tasawar-baig.webp": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAQCdASoIAAoABABoJYwCdAEfbQOkcAAA/rN2X8lXPxTaXhW6Act2h0PLkiyIqUsy+M3LBHGH5AN4oAA=",
  "/images/team/team-hero-2026-08.webp": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoIAAUABABoJYwCdAEOO/CwAMtBZFyssBnKET6p2HDGJCBQJJw3xv9AAAA=",
  "/images/team/tomasz-kowalczewski.webp": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQAgCdASoIAAoABABoJZQCw7EO6TEoB7QAAPZ3JqRGQlgfMcyU1guQgmzNK7pGXGltZTPCK5+vR01BuueB3wlIajwAAA==",
};
