export type BlogTopic =
  | "climate-science"
  | "policy"
  | "energy"
  | "community"
  | "technology";

/**
 * A run of body text. A plain string renders as-is; an object renders as a
 * link. Splitting paragraphs this way keeps the prose in the content file
 * and out of JSX, so the wording stays exactly as the author wrote it.
 *
 * Every href below was read out of the author's source PDF — each is a real
 * link annotation, matched to its anchor text by rectangle position. Do not
 * add links here that are not in the author's original.
 */
export type BlogSegment =
  | string
  | {
      text: string;
      href: string;
    };

export type BlogPost = {
  slug: string;
  title: string;
  excerpt: string;
  topic: BlogTopic;
  topicLabel: string;
  readingTime: string;
  author: string;
  /**
   * Publication date as YYYY-MM-DD. Feeds datePublished in the Article
   * structured data, orders the index, and is what search engines read as a
   * freshness signal — the reason to set it on every new post.
   *
   * Optional only because the two posts written before this field existed
   * have no recorded date, and inventing one would be a lie in schema.org
   * markup. Set it on everything from here on.
   */
  date?: string;
  /** Optional thumbnail. Falls back to a gradient panel when absent. */
  image?: string;
  body: readonly (readonly BlogSegment[])[];
  featured?: boolean;
};

export const blogContent = {
  hero: {
    eyebrow: "Blog",

    title:
      "Climate commentary, field notes and perspective.",

    description:
      "Shorter, faster writing from the ClimateWatch team — reflections from negotiations and fieldwork, explainers on climate science, and commentary on the decisions shaping Pakistan’s climate future.",
  },

  distinction: {
    eyebrow: "Blog vs publications",

    title:
      "Commentary here, formal research in Publications.",

    description:
      "The blog carries opinion, explainers and field reporting written in the author’s voice. Peer-reviewed research, policy reports and briefings — with downloadable PDFs — live in the publications archive.",

    linkLabel:
      "Go to publications",

    href: "/publications",
  },

  topics: [
    {
      value: "all",
      label: "All posts",
    },
    {
      value: "climate-science",
      label: "Climate science",
    },
    {
      value: "technology",
      label: "Technology",
    },
  ],

  posts: [
    {
      /*
       * Text taken verbatim from the author's document. The extraction
       * dropped some inter-word spacing — "burningfuel", "42.6%of",
       * "industrialprocessesmake" — and those spaces are restored here.
       * No wording is changed.
       *
       * All four hyperlinks come from the PDF's own link annotations,
       * matched to their anchor text by comparing each annotation rectangle
       * against the positions of the text runs. None were added.
       */
      slug: "the-carbon-league",
      date: "2026-08-25",

      title:
        "The Carbon League: Top Emitters of Global Emissions",

      excerpt:
        "Global emissions peaked at 50.8 gigatons in 2023. Three countries account for 42.6% of them, and one sector for three quarters — a look at who is driving climate change and why it matters.",

      topic: "climate-science",
      topicLabel: "Climate science",

      image:
        "/images/blog/the-carbon-league.webp",

      readingTime: "3 min read",
      author: "Habiba Tariq",

      body: [
        [
          "CO2 emissions are higher today than at any time in recorded human history. Human activity throughout the years has led humanity directly to this precarious and unprecedented state, which is adversely affecting our planet and environmental conditions. There have been decades of historic warnings, international summits, and programs aiming to grow public awareness, and still, the collective carbon footprint of countries around the world remains relentlessly high and continues to rise. This is not a door-knock warning; we are standing at this critical juncture this time.",
        ],
        [
          "Before we dive further, we must first unpack what a carbon footprint actually represents. The carbon footprint defines human activity through the lens of atmospheric impact, measuring the total quantity of greenhouse gases, primarily carbon dioxide and methane, generated by our daily choices, economic systems, and industrial infrastructure. It captures both direct emissions, such as burning fuel in an automobile, and indirect emissions, such as the electricity required to power home appliances or the supply chain energy needed to manufacture and transport consumer goods. When aggregated across billions of humans' daily activities and millions of factories worldwide, the carbon footprint appears to be the unmistakable strain on the biosphere.",
        ],
        [
          {
            text: "Historical data",
            href: "https://www.climatewatchdata.org/ghg-emissions?end_year=2023&start_year=1990",
          },
          " give us an understanding of the relentless pace of global emissions over recent decades, culminating in a peak of 50.8 gigatons of carbon dioxide equivalent in 2023. While the overarching trend shows steady growth, there have been brief moments where emissions temporarily fell. Notably, in 2020, during the height of the COVID-19 pandemic, ",
          {
            text: "global emissions decreased by 5.4%",
            href: "https://www.jpl.nasa.gov/news/emission-reductions-from-pandemic-had-unexpected-effects-on-atmosphere/",
          },
          ". This represented the largest single-year drop in emissions recorded because of worldwide lockdowns, grounded commercial flights, reduced industrial manufacturing, as well as the drop in daily commuting. However, this temporary dip did not signify a structural shift toward sustainability. As health restrictions eased and economies reopened in 2021, global emissions hiked right back up, rapidly erasing the momentary atmospheric relief and returning to their upward trajectory.",
        ],
        [
          "When examining the geographical distribution of global emissions, the burden is heavily concentrated among a small number of industrial powers. Out of all the nations in the world, ",
          {
            text: "the top ten emitting countries",
            href: "https://www.wri.org/insights/interactive-chart-shows-changes-worlds-top-10-emitters?ap3c=IGqGtwiUu_Ub28AIAGqGtwjSxghelMRaCiUP5W4qiwGqT1l_sg&_gl=1*x0icqi*_gcl_au*MTE0MzM0MDEwNy4xNzg3MjEzNTc0",
          },
          " produce the vast majority of global carbon pollution, with just three giant nations. China, the United States, and India all together account for 42.6% of total global emissions. These three economic tycoons drive immense global demand for coal, oil, and natural gas to power their massive populations, industrial manufacturing hubs, and sprawling urban centers. Their dominant share of emissions underscores the reality that global climate stabilization is impossible without aggressive decarbonization policies within these few key nations.",
        ],
        [
          "The root cause of these rising emissions is specific human activities that generate the most pollution. Among all economic sectors, the energy sector is the biggest sector among all, acting as the primary driver of global climate change. In 2019, ",
          {
            text: "the energy sector was responsible for 76.7% of total global greenhouse gas emissions",
            href: "https://www.wri.org/insights/4-charts-explain-greenhouse-gas-emissions-countries-and-sectors",
          },
          ". This sector encompasses a wide variety of fundamental human operations, most notably the generation of heat and electricity, which relies heavily on burning fossil fuels like coal and natural gas. Beyond power plants, the energy sector includes the fuel consumed across the transport sector, including cars, trucks, ships, and airplanes, as well as the energy needed for heating, cooling, and powering commercial and residential buildings. Furthermore, the rest of the top sectors include ",
          {
            text: "agriculture at 12.3%, industrial processes make up 6.2%, and waste emissions are 3.8%",
            href: "https://www.wri.org/insights/4-charts-explain-greenhouse-gas-emissions-countries-and-sectors",
          },
          " of the global total.",
        ],
        [
          "The data explicitly shows that higher emissions are leading to higher economic growth for the countries producing them, but adversely affecting the whole world, especially the countries that are not contributing to it at all. This is the pattern countries have followed in the chase for economic growth since the Industrial Revolution. No matter how many international conferences, summits, and voices raised on this global catastrophe, results will only come once it becomes a priority for every soul on this planet.",
        ],
      ],
    },
    {
      slug: "rising-the-heat-declining-the-productivity",
      date: "2026-07-09",

      title:
        "Rising the Heat, Declining the Productivity",

      excerpt:
        "Pakistan is one of the countries in the world facing the wrath of climate change every year in the form of disasters, disturbed weather patterns, and extreme heat strokes.",

      topic: "climate-science",

      topicLabel: "Climate science",

      image:
        "/images/blog/rising-the-heat-declining-the-productivity.webp",

      readingTime: "4 min read",

      author: "Habiba Tariq",

      featured: true,

      body: [
        [
          "Pakistan is one of the countries in the world facing the wrath of climate change every year in the form of disasters, disturbed weather patterns, and extreme heat strokes. Once again, it is recorded to be the second-warmest year in 65 years. According to the ",
          {
            text: "Economic Survey 2025-26",
            href: "https://finance.gov.pk/survey_2026.html",
          },
          ", the national annual mean temperature in 2025 reached 23.9°C, which is 1.09°C above the long-term average of 22.8°C. On its own, these numbers are deciding and carving how people of this country will live and work. This excessive and rising heat is not just warmth but a gesture of hellfire in which Pakistan is burning for other countries' vices.",
        ],
        [
          "This key unfairness is that Pakistan has barely contributed to the problem it is now living through. The country contributes to evident for less than 1% of global emissions today and just 0.4% historically. But still it continues to rank among the most climate-vulnerable nations in the world. This gap between responsibility and consequence is not new, but each hot year makes it harder to live through and ignore. The country's annual mean temperature has already climbed by about 0.5°C, and projections suggest a 3 to 5°C rise by the end of the century if nothing changes globally. That trajectory is not some far-off scenario. It is already visible in the numbers coming out of this year alone.",
        ],
        [
          "The clearest evidence of this shift is already ",
          {
            text: "affecting the north",
            href: "https://newlinesmag.com/reportage/pakistan-is-losing-its-glaciers-to-climate-change/",
          },
          ", where the glaciers of Gilgit-Baltistan and Khyber Pakhtunkhwa are retreating, and the water bodies they feed are shrinking. These glaciers are not just a single concern; in reality, they feed the Indus system that much of the country's agriculture, hydropower, and drinking water depends on. As they retreat, rainfall patterns downstream become harder to predict too, swinging between prolonged dry spells and sudden, intense flooding within the same year.",
        ],
        [
          "It is this same unpredictability, along with rising heat, that is starting to show up in something more immediate: human health. Prolonged heat exposure doesn't just make people uncomfortable, it causes real damage to the human body, especially for those who cannot escape it. Heatstroke, dehydration, and cardiovascular stress rise sharply during extreme heat events, and Pakistan has already recorded deaths in Jamshoro tied directly to heatwaves. But the deeper story is in who bears this burden. It is disproportionately the poor, and specifically outdoor laborers, construction workers, farmers, and street vendors, who have no option but to keep working through the hottest hours of the day because their income depends on it. They cannot afford air conditioning, and many cannot afford to lose a day's wage either, so they keep working in conditions that are actively damaging their health and draining their energy.",
        ],
        [
          "These people burning in Pakistan are its ",
          {
            text: "human capital",
            href: "https://cri.org/wp-content/uploads/2025/12/Heat-does-to-our-bodies_CRI-Pakistan-Report.pdf?curius=4580",
          },
          ". When workers are pushed to labor through extreme heat, their productivity drops, their risk of illness and injury rises, and, over time, their capacity to work consistently declines. This is not just a personal health issue, it becomes a human capital issue for the country as a whole. A workforce that is chronically exposed to heat stress is a workforce that produces less, misses more workdays, and faces higher long-term health costs, and in an economy like Pakistan's, where a large share of labor is informal and unprotected, there is no safety net absorbing that loss. It falls directly on the individual and, in aggregate, on the economy.",
        ],
        [
          "Layered on top of all this is ",
          {
            text: "El Niño",
            href: "https://www.dawn.com/news/2006917",
          },
          ", a natural climate pattern where sea surface temperatures in the central and eastern Pacific warm periodically and disrupt weather systems worldwide. El Niño years tend to push ",
          {
            text: "global temperatures",
            href: "https://www.dawn.com/news/2002230",
          },
          " higher, and Pakistan is not shielded from that effect. When a naturally recurring warming cycle overlaps with a steady, human-driven warming trend that is already underway, the two compound each other. Hot years are becoming more frequent, and the recovery window requires policy solutions, both for the land and for the people working on it.",
        ],
        [
          "Pakistan does have climate frameworks in place, including its National Climate Change Policy and its Nationally Determined Contributions under the ",
          {
            text: "Paris Agreement",
            href: "https://www.un.org/en/climatechange/paris-agreement",
          },
          ", both of which name adaptation in water, agriculture, and health as priorities. But the distance between what these policies promise and what reaches a daily-wage worker standing in 45-degree heat is still wide. The Economic Survey's numbers are not just a record to note and move past. They signal the condition and the reality, showing how we are treating our people and how much priority they truly have.",
        ],
      ],
    },

    {
      slug: "thirsty-ai",
      date: "2026-07-04",

      title: "Thirsty AI",

      excerpt:
        "We are in the age of artificial intelligence that people a hundred years ago could not have imagined, and a hundred years later, it is everyone's pocket buddy.",

      topic: "technology",

      topicLabel: "Technology",

      image:
        "/images/blog/thirsty-ai.webp",

      readingTime: "4 min read",

      author: "Habiba Tariq",

      body: [
        [
          "We are in the age of artificial intelligence that people a hundred years ago could not have imagined, and a hundred years later, it is everyone's pocket buddy. AI first captured the public's attention when it turned into chatbots, and people have been using it like a feast ever since, unaware of the fact that their responses are turning into training data for these systems.",
        ],
        [
          "For most people, AI is just a concept of chatbots, but in the real domain, these are large, enormous data centers, high-maintenance infrastructures that require billions of dollars to build. These data centers not only span acres of land and consume electricity but also require tons of water. Whenever you ask AI a pressing question, the servers run and generate an intense amount of heat. To prevent overheating, these centers need water. An immense amount of water to cool down their temperature.",
        ],
        [
          "The scale of this consumption is staggering. A 2024 report from the Lawrence Berkeley National Laboratory estimated that in 2023, data centers in the US consumed over 17 billion gallons of water for cooling alone. The irony is that Trump, in 2025, announced a dedication of 500 billion dollars to build AI infrastructure through the Stargate Project, which could make these figures double or even quadruple. The same report estimated that in 2023, U.S. data centers consumed an additional 211 billion gallons (800 billion liters) of water indirectly through the electricity that powers them. But that is just an estimate, because these big tech tycoons never reveal how much water their data centers actually consume. Estimates show that a single AI conversation of around fifty responses consumes roughly half a liter of water. Microsoft's global water consumption increased by thirty-four percent due to AI expansion. In 2023, Google reported ",
          {
            text: "consuming over 6 billion gallons of water",
            href: "https://www.gstatic.com/gumdrop/sustainability/google-2024-environmental-report.pdf",
          },
          " (nearly 23 billion liters) to cool all its data centers, and Meta's data centers consumed 776 million gallons of water in the same year.",
        ],
        [
          "On one side, these big tycoons promise a big, bright future, but humans cannot have a bright future without water, which is the most essential and basic need. Humans can live without AI. In fact, we have lived without AI. Generations have lived without AI. But now the cost of Big Tech is going beyond human value and Earth's capacity. As water reserves deplete, there are direct repercussions for water-bankrupt regions, where about 3 billion people and more than ",
          {
            text: "half of global food production",
            href: "https://youtu.be/2V7bBi21o9g?si=dfNis6HdSGuk8hn1",
          },
          " are concentrated.",
        ],
        [
          "And it is not finished yet. AI is still being trained and expanding, and large AI models like GPT-4 are estimated to have consumed around 700,000 liters of water during training. These are the projects of rich countries, and ultimately, they are the ones who will benefit. It is the same situation as when big countries polluted the environment beforehand, generated millions of dollars, and named themselves among thriving economies, but the negative effects were, and still are, faced by the Global South. Pakistan, which ranks among the most climate-vulnerable countries in the world, is no exception. It also lies among water-stressed countries, and as per the International Organisation for Migration (IOM), Pakistan is ",
          {
            text: "predicted",
            href: "https://dtm.iom.int/youthengagement/flooded-yet-thirsty-climate-disaster-and-water-access-pakistan-during-2022-2023",
          },
          " to slip into absolute water scarcity by 2035, as its large population and inability to conserve fresh water are leading it toward despair.",
        ],
        [
          "Over this, countries including the US, UAE, and Saudi Arabia are building massive AI infrastructure while consuming freshwater at an industrial scale. The opportunity cost will be borne by underprivileged countries once again. Every year, nature gives us a water income in the form of rain, snow, and stored glaciers. Water is limited, as is the nature of every resource on Earth, but humanity is wasting it on machines rather than saving it for generations to come. We can indeed live without AI, but we will surely wither without water.",
        ],
      ],
    },
  ] as readonly BlogPost[],

  closing: {
    eyebrow: "Write with us",

    title:
      "We publish contributed climate commentary.",

    description:
      "If you work on climate policy, research, energy or community resilience and want to write for the ClimateWatch blog, send us an outline.",

    email:
      "info@climatewatch-nccb.org",
  },
} as const;
