"use client";

import Image from "next/image";
import type { ImageProps } from "next/image";
import { useState } from "react";

import { imageBlur } from "@/lib/image-blur";

type LoadedImageProps = ImageProps & {
  loaderClassName?: string;
  darkLoader?: boolean;
};

export function LoadedImage({
  className = "",
  loaderClassName = "",
  darkLoader = false,
  onLoad,
  ...props
}: Readonly<LoadedImageProps>) {
  const [isLoaded, setIsLoaded] =
    useState(false);

  /*
   * A priority image is the one the page is judged on. Fading it in costs
   * exactly what Largest Contentful Paint measures: the browser painted it at
   * opacity 0, then waited for hydration, the load event, a re-render and a
   * one-second transition before it counted as painted.
   *
   * So priority images skip the shimmer and appear as soon as the bytes
   * arrive. Everything below the fold keeps the fade, where it costs nothing
   * and reads better than a pop-in.
   */
  const revealImmediately = Boolean(
    props.priority,
  );
  const shown =
    isLoaded || revealImmediately;

  /*
   * A tiny base64 version of the same photograph, generated by
   * scripts/generate-image-blur.mjs. next/image paints it immediately and
   * loads the real file underneath, so the frame is never empty — which
   * matters most on a slow connection, where a 400 KB hero is otherwise
   * several seconds of shimmer.
   *
   * Only string sources can be looked up, and an image added without
   * re-running the generator simply will not be found, so the shimmer stays
   * as the fallback for both cases.
   */
  const blurDataUrl =
    typeof props.src === "string"
      ? imageBlur[props.src]
      : undefined;

  return (
    <div className="relative h-full w-full overflow-hidden">
      {/* Loader */}
      <div
        aria-hidden="true"
        className={[
          "pointer-events-none absolute inset-0 z-10 overflow-hidden transition-opacity duration-700",
          darkLoader
            ? "bg-primary-dark"
            : "bg-surface-muted",
          shown
            ? "opacity-0"
            : "opacity-100",
          loaderClassName,
        ].join(" ")}
      >
        <div className="absolute inset-0 overflow-hidden">
          <span
            className={[
              "image-loader-shimmer absolute inset-y-0 left-[-45%] w-[45%]",
              darkLoader
                ? "bg-gradient-to-r from-transparent via-white/15 to-transparent"
                : "bg-gradient-to-r from-transparent via-white/65 to-transparent",
            ].join(" ")}
          />
        </div>

        <div className="absolute bottom-5 left-5 flex items-center gap-3">
          <span
            className={[
              "relative size-2 shrink-0",
              darkLoader
                ? "bg-secondary"
                : "bg-primary",
            ].join(" ")}
          >
            <span
              className={[
                "absolute inset-0 animate-ping opacity-40",
                darkLoader
                  ? "bg-secondary"
                  : "bg-primary",
              ].join(" ")}
            />
          </span>

          <span
            className={[
              "text-[0.6875rem] font-bold uppercase tracking-[0.12em]",
              darkLoader
                ? "text-white/60"
                : "text-primary/55",
            ].join(" ")}
          >
            Loading image
          </span>
        </div>
      </div>

      <Image
        {...props}
        {...(blurDataUrl
          ? {
              placeholder: "blur" as const,
              blurDataURL: blurDataUrl,
            }
          : {})}
        className={[
          "transition-[opacity,transform,filter] duration-1000 ease-out",
          shown
            ? "opacity-100 blur-0"
            : "opacity-0 blur-[2px]",
          className,
        ].join(" ")}
        onLoad={(event) => {
          setIsLoaded(true);
          onLoad?.(event);
        }}
      />
    </div>
  );
}